[versions]
appVersion = "1.0.0"

## Android SDK versions
minAndroidSdk = "19"
targetAndroidSdk = "32"
compileAndroidSdk = "32"

## iOS versions
iosDeploymentTarget = "12.0"

## Dependencies' versions
kotlin = "1.7.0"

[libraries]
google-material = { module = "com.google.android.material:material", version = "1.6.1" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.2" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }

gradlePlugin-android = { module = "com.android.tools.build:gradle", version = "7.2.1" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.6.21" }

# [bundles]
# [plugins]
